In [1]:
import pandas as pd

In [9]:
df = pd.read_csv(r'C:\Users\kalle\Documents\Github\data_vizualization_karl_de25\data\salaries.csv')

df.head(3)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2024,SE,FT,AI Engineer,202730,USD,202730,US,0,US,M
1,2024,SE,FT,AI Engineer,92118,USD,92118,US,0,US,M
2,2024,SE,FT,Data Engineer,130500,USD,130500,US,0,US,M

In [11]:
unique_jobs = df['job_title'].nunique()
unique_jobs

155

In [27]:
unique_years = df['work_year'].nunique()
unique_years

5

In [14]:
unique_countries = df['company_location'].unique()
unique_countries

array(['US', 'AU', 'GB', 'CA', 'NL', 'LT', 'DK', 'FR', 'ZA', 'NZ', 'AR',
       'ES', 'KE', 'LV', 'IN', 'DE', 'IL', 'FI', 'AT', 'BR', 'CH', 'AE',
       'PL', 'SA', 'UA', 'EG', 'PH', 'TR', 'OM', 'MX', 'PT', 'BA', 'IT',
       'AS', 'IE', 'EE', 'MT', 'HU', 'LB', 'RO', 'VN', 'NG', 'LU', 'GI',
       'CO', 'SI', 'GR', 'MU', 'RU', 'KR', 'CZ', 'QA', 'GH', 'SE', 'AD',
       'EC', 'NO', 'JP', 'HK', 'CF', 'SG', 'TH', 'HR', 'AM', 'PK', 'IR',
       'BS', 'PR', 'BE', 'ID', 'MY', 'HN', 'DZ', 'IQ', 'CN', 'CL', 'MD'],
      dtype=object)

In [15]:
unique_sizes = df['company_size'].unique()
unique_sizes

array(['M', 'L', 'S'], dtype=object)

In [24]:
remote = df['remote_ratio'].value_counts(dropna=False)
remote

remote_ratio
0      11118
100     5167
50       249
Name: count, dtype: int64

In [25]:
average_salary_per_role = df.groupby('job_title').mean(numeric_only=True)
average_salary_per_role

,work_year,salary,salary_in_usd,remote_ratio
job_title,,,,
AI Architect,2023.517241,252001.724138,252551.241379,31.034483
AI Developer,2023.000000,134684.210526,135466.789474,42.105263
AI Engineer,2023.591667,163626.866667,162730.508333,23.333333
AI Product Manager,2023.666667,141766.666667,141766.666667,16.666667
AI Programmer,2023.000000,764400.857143,62042.000000,42.857143
...,...,...,...,...
Sales Data Analyst,2020.000000,60000.000000,60000.000000,0.000000
Software Data Engineer,2023.000000,120000.000000,111627.666667,83.333333
Staff Data Analyst,2021.000000,84999.333333,79917.000000,50.000000
Staff Data Scientist,2020.500000,134500.000000,134500.000000,75.000000
Staff Machine Learning Engineer,2021.000000,185000.000000,185000.000000,50.000000

In [28]:
median_salary_per_role = df.groupby('job_title').median(numeric_only=True)
median_salary_per_role

,work_year,salary,salary_in_usd,remote_ratio
job_title,,,,
AI Architect,2024.0,204000.0,204000.0,0.0
AI Developer,2023.0,124000.0,124000.0,50.0
AI Engineer,2024.0,166000.0,166000.0,0.0
AI Product Manager,2024.0,120000.0,120000.0,0.0
AI Programmer,2023.0,70000.0,60207.0,0.0
...,...,...,...,...
Sales Data Analyst,2020.0,60000.0,60000.0,0.0
Software Data Engineer,2023.0,100000.0,74883.0,100.0
Staff Data Analyst,2020.0,60000.0,44753.0,50.0
Staff Data Scientist,2020.5,134500.0,134500.0,75.0
Staff Machine Learning Engineer,2021.0,185000.0,185000.0,50.0

In [29]:
avg_sal_per_seniority = df.groupby('experience_level').mean(numeric_only=True)
avg_sal_per_seniority

                    work_year         salary  salary_in_usd  remote_ratio
experience_level
EN                2023.307170  125831.628679   92327.413585     31.018868
EX                2023.261477  208064.343313  195264.281437     36.027944
MI                2023.301882  157116.976721  125923.131253     28.751857
SE                2023.186879  168852.493440  163662.826148     33.167760

In [30]:
median_sal_per_seniority = df.groupby('experience_level').median(numeric_only=True)
median_sal_per_seniority

                  work_year    salary  salary_in_usd  remote_ratio
experience_level
EN                   2024.0   84068.0        83000.0           0.0
EX                   2023.0  194500.0       192000.0           0.0
MI                   2023.0  115601.0       115000.0           0.0
SE                   2023.0  155000.0       155000.0           0.0

In [32]:
remote_avg_salary = df.groupby('remote_ratio')['salary'].median(numeric_only=True)
remote_avg_salary

remote_ratio
0      143000.0
50      85000.0
100    141300.0
Name: salary, dtype: float64

In [33]:
location_avg_salary = df.groupby('company_location')['salary'].median(numeric_only=True)
location_avg_salary

company_location
AD     47000.0
AE     90000.0
AM     50000.0
AR     60000.0
AS     50000.0
        ...
TR    103500.0
UA     84000.0
US    147500.0
VN     60000.0
ZA     44263.0
Name: salary, Length: 77, dtype: float64